name = "OptParse"
uuid = "1244ff17-1aa7-4121-9347-f4ead108e58f"
version = "0.1.0"
authors = ["ghyatzo <dev@cschen.cc>"]

[workspace]
projects = ["test", "docs"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ErrorTypes = "7f495686-c6d2-4c77-9e8e-e4c865675f9d"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
WrappedUnions = "325db55a-9c6c-5b90-b1a2-ec87e7a38c44"

[compat]
Accessors = "0.1.42"
ErrorTypes = "0.5.2"
UUIDs = "1.11.0"
WrappedUnions = "0.3.3"
